# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: face-recognition.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='face-recognition.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x16\x66\x61\x63\x65-recognition.proto\x12\x08protobuf\"I\n\x12MakeDataSetRequest\x12\x11\n\twebcamPos\x18\x01 \x01(\r\x12\x0e\n\x06userID\x18\x02 \x01(\t\x12\x10\n\x08username\x18\x03 \x01(\t\"\"\n\x13MakeDataSetResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x0e\n\x0cTrainRequest\"\x1c\n\rTrainResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"?\n\x14\x46\x61\x63\x65RecognizeRequest\x12\x11\n\twebcamPos\x18\x01 \x01(\r\x12\x14\n\x0csubWebcamPos\x18\x02 \x01(\r\"$\n\x15\x46\x61\x63\x65RecognizeResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t2\xf4\x01\n\x14\x46\x61\x63\x65RecognizeService\x12L\n\x0bmakeDataset\x12\x1c.protobuf.MakeDataSetRequest\x1a\x1d.protobuf.MakeDataSetResponse\"\x00\x12:\n\x05train\x12\x16.protobuf.TrainRequest\x1a\x17.protobuf.TrainResponse\"\x00\x12R\n\rfaceRecognize\x12\x1e.protobuf.FaceRecognizeRequest\x1a\x1f.protobuf.FaceRecognizeResponse\"\x00\x62\x06proto3'
)




_MAKEDATASETREQUEST = _descriptor.Descriptor(
  name='MakeDataSetRequest',
  full_name='protobuf.MakeDataSetRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='webcamPos', full_name='protobuf.MakeDataSetRequest.webcamPos', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='userID', full_name='protobuf.MakeDataSetRequest.userID', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='username', full_name='protobuf.MakeDataSetRequest.username', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=36,
  serialized_end=109,
)


_MAKEDATASETRESPONSE = _descriptor.Descriptor(
  name='MakeDataSetResponse',
  full_name='protobuf.MakeDataSetResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.MakeDataSetResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=111,
  serialized_end=145,
)


_TRAINREQUEST = _descriptor.Descriptor(
  name='TrainRequest',
  full_name='protobuf.TrainRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=147,
  serialized_end=161,
)


_TRAINRESPONSE = _descriptor.Descriptor(
  name='TrainResponse',
  full_name='protobuf.TrainResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.TrainResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=163,
  serialized_end=191,
)


_FACERECOGNIZEREQUEST = _descriptor.Descriptor(
  name='FaceRecognizeRequest',
  full_name='protobuf.FaceRecognizeRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='webcamPos', full_name='protobuf.FaceRecognizeRequest.webcamPos', index=0,
      number=1, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='subWebcamPos', full_name='protobuf.FaceRecognizeRequest.subWebcamPos', index=1,
      number=2, type=13, cpp_type=3, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=193,
  serialized_end=256,
)


_FACERECOGNIZERESPONSE = _descriptor.Descriptor(
  name='FaceRecognizeResponse',
  full_name='protobuf.FaceRecognizeResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.FaceRecognizeResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=258,
  serialized_end=294,
)

DESCRIPTOR.message_types_by_name['MakeDataSetRequest'] = _MAKEDATASETREQUEST
DESCRIPTOR.message_types_by_name['MakeDataSetResponse'] = _MAKEDATASETRESPONSE
DESCRIPTOR.message_types_by_name['TrainRequest'] = _TRAINREQUEST
DESCRIPTOR.message_types_by_name['TrainResponse'] = _TRAINRESPONSE
DESCRIPTOR.message_types_by_name['FaceRecognizeRequest'] = _FACERECOGNIZEREQUEST
DESCRIPTOR.message_types_by_name['FaceRecognizeResponse'] = _FACERECOGNIZERESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

MakeDataSetRequest = _reflection.GeneratedProtocolMessageType('MakeDataSetRequest', (_message.Message,), {
  'DESCRIPTOR' : _MAKEDATASETREQUEST,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.MakeDataSetRequest)
  })
_sym_db.RegisterMessage(MakeDataSetRequest)

MakeDataSetResponse = _reflection.GeneratedProtocolMessageType('MakeDataSetResponse', (_message.Message,), {
  'DESCRIPTOR' : _MAKEDATASETRESPONSE,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.MakeDataSetResponse)
  })
_sym_db.RegisterMessage(MakeDataSetResponse)

TrainRequest = _reflection.GeneratedProtocolMessageType('TrainRequest', (_message.Message,), {
  'DESCRIPTOR' : _TRAINREQUEST,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TrainRequest)
  })
_sym_db.RegisterMessage(TrainRequest)

TrainResponse = _reflection.GeneratedProtocolMessageType('TrainResponse', (_message.Message,), {
  'DESCRIPTOR' : _TRAINRESPONSE,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.TrainResponse)
  })
_sym_db.RegisterMessage(TrainResponse)

FaceRecognizeRequest = _reflection.GeneratedProtocolMessageType('FaceRecognizeRequest', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNIZEREQUEST,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.FaceRecognizeRequest)
  })
_sym_db.RegisterMessage(FaceRecognizeRequest)

FaceRecognizeResponse = _reflection.GeneratedProtocolMessageType('FaceRecognizeResponse', (_message.Message,), {
  'DESCRIPTOR' : _FACERECOGNIZERESPONSE,
  '__module__' : 'face_recognition_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.FaceRecognizeResponse)
  })
_sym_db.RegisterMessage(FaceRecognizeResponse)



_FACERECOGNIZESERVICE = _descriptor.ServiceDescriptor(
  name='FaceRecognizeService',
  full_name='protobuf.FaceRecognizeService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=297,
  serialized_end=541,
  methods=[
  _descriptor.MethodDescriptor(
    name='makeDataset',
    full_name='protobuf.FaceRecognizeService.makeDataset',
    index=0,
    containing_service=None,
    input_type=_MAKEDATASETREQUEST,
    output_type=_MAKEDATASETRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='train',
    full_name='protobuf.FaceRecognizeService.train',
    index=1,
    containing_service=None,
    input_type=_TRAINREQUEST,
    output_type=_TRAINRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='faceRecognize',
    full_name='protobuf.FaceRecognizeService.faceRecognize',
    index=2,
    containing_service=None,
    input_type=_FACERECOGNIZEREQUEST,
    output_type=_FACERECOGNIZERESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_FACERECOGNIZESERVICE)

DESCRIPTOR.services_by_name['FaceRecognizeService'] = _FACERECOGNIZESERVICE

# @@protoc_insertion_point(module_scope)
