# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
import grpc

import face_recognition_pb2 as face__recognition__pb2


class FaceRecognizeServiceStub(object):
    """FaceRecognizeService ...
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.makeDataset = channel.unary_unary(
                '/protobuf.FaceRecognizeService/makeDataset',
                request_serializer=face__recognition__pb2.MakeDataSetRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.MakeDataSetResponse.FromString,
                )
        self.train = channel.unary_unary(
                '/protobuf.FaceRecognizeService/train',
                request_serializer=face__recognition__pb2.TrainRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.TrainResponse.FromString,
                )
        self.faceRecognize = channel.unary_unary(
                '/protobuf.FaceRecognizeService/faceRecognize',
                request_serializer=face__recognition__pb2.FaceRecognizeRequest.SerializeToString,
                response_deserializer=face__recognition__pb2.FaceRecognizeResponse.FromString,
                )


class FaceRecognizeServiceServicer(object):
    """FaceRecognizeService ...
    """

    def makeDataset(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def train(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def faceRecognize(self, request, context):
        """Missing associated documentation comment in .proto file"""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_FaceRecognizeServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'makeDataset': grpc.unary_unary_rpc_method_handler(
                    servicer.makeDataset,
                    request_deserializer=face__recognition__pb2.MakeDataSetRequest.FromString,
                    response_serializer=face__recognition__pb2.MakeDataSetResponse.SerializeToString,
            ),
            'train': grpc.unary_unary_rpc_method_handler(
                    servicer.train,
                    request_deserializer=face__recognition__pb2.TrainRequest.FromString,
                    response_serializer=face__recognition__pb2.TrainResponse.SerializeToString,
            ),
            'faceRecognize': grpc.unary_unary_rpc_method_handler(
                    servicer.faceRecognize,
                    request_deserializer=face__recognition__pb2.FaceRecognizeRequest.FromString,
                    response_serializer=face__recognition__pb2.FaceRecognizeResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'protobuf.FaceRecognizeService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))


 # This class is part of an EXPERIMENTAL API.
class FaceRecognizeService(object):
    """FaceRecognizeService ...
    """

    @staticmethod
    def makeDataset(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.FaceRecognizeService/makeDataset',
            face__recognition__pb2.MakeDataSetRequest.SerializeToString,
            face__recognition__pb2.MakeDataSetResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def train(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.FaceRecognizeService/train',
            face__recognition__pb2.TrainRequest.SerializeToString,
            face__recognition__pb2.TrainResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)

    @staticmethod
    def faceRecognize(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(request, target, '/protobuf.FaceRecognizeService/faceRecognize',
            face__recognition__pb2.FaceRecognizeRequest.SerializeToString,
            face__recognition__pb2.FaceRecognizeResponse.FromString,
            options, channel_credentials,
            call_credentials, compression, wait_for_ready, timeout, metadata)
