# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: user-service.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='user-service.proto',
  package='protobuf',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x12user-service.proto\x12\x08protobuf\" \n\x04User\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\")\n\rInsertRequest\x12\n\n\x02id\x18\x01 \x01(\t\x12\x0c\n\x04name\x18\x02 \x01(\t\"\x1d\n\x0eInsertResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\"\x0f\n\rGetAllRequest\"<\n\x0eGetAllResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x1d\n\x05users\x18\x02 \x03(\x0b\x32\x0e.protobuf.User\"\x1c\n\x0eGetByIDRequest\x12\n\n\x02id\x18\x01 \x01(\t\"<\n\x0fGetByIDResponse\x12\x0b\n\x03msg\x18\x01 \x01(\t\x12\x1c\n\x04user\x18\x02 \x01(\x0b\x32\x0e.protobuf.User2\xcd\x01\n\x0bUserService\x12=\n\x06insert\x12\x17.protobuf.InsertRequest\x1a\x18.protobuf.InsertResponse\"\x00\x12=\n\x06getAll\x12\x17.protobuf.GetAllRequest\x1a\x18.protobuf.GetAllResponse\"\x00\x12@\n\x07getByID\x12\x18.protobuf.GetByIDRequest\x1a\x19.protobuf.GetByIDResponse\"\x00\x62\x06proto3'
)




_USER = _descriptor.Descriptor(
  name='User',
  full_name='protobuf.User',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.User.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.User.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=32,
  serialized_end=64,
)


_INSERTREQUEST = _descriptor.Descriptor(
  name='InsertRequest',
  full_name='protobuf.InsertRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.InsertRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='name', full_name='protobuf.InsertRequest.name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=66,
  serialized_end=107,
)


_INSERTRESPONSE = _descriptor.Descriptor(
  name='InsertResponse',
  full_name='protobuf.InsertResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.InsertResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=109,
  serialized_end=138,
)


_GETALLREQUEST = _descriptor.Descriptor(
  name='GetAllRequest',
  full_name='protobuf.GetAllRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=140,
  serialized_end=155,
)


_GETALLRESPONSE = _descriptor.Descriptor(
  name='GetAllResponse',
  full_name='protobuf.GetAllResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.GetAllResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='users', full_name='protobuf.GetAllResponse.users', index=1,
      number=2, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=157,
  serialized_end=217,
)


_GETBYIDREQUEST = _descriptor.Descriptor(
  name='GetByIDRequest',
  full_name='protobuf.GetByIDRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='id', full_name='protobuf.GetByIDRequest.id', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=219,
  serialized_end=247,
)


_GETBYIDRESPONSE = _descriptor.Descriptor(
  name='GetByIDResponse',
  full_name='protobuf.GetByIDResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='msg', full_name='protobuf.GetByIDResponse.msg', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='user', full_name='protobuf.GetByIDResponse.user', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=249,
  serialized_end=309,
)

_GETALLRESPONSE.fields_by_name['users'].message_type = _USER
_GETBYIDRESPONSE.fields_by_name['user'].message_type = _USER
DESCRIPTOR.message_types_by_name['User'] = _USER
DESCRIPTOR.message_types_by_name['InsertRequest'] = _INSERTREQUEST
DESCRIPTOR.message_types_by_name['InsertResponse'] = _INSERTRESPONSE
DESCRIPTOR.message_types_by_name['GetAllRequest'] = _GETALLREQUEST
DESCRIPTOR.message_types_by_name['GetAllResponse'] = _GETALLRESPONSE
DESCRIPTOR.message_types_by_name['GetByIDRequest'] = _GETBYIDREQUEST
DESCRIPTOR.message_types_by_name['GetByIDResponse'] = _GETBYIDRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

User = _reflection.GeneratedProtocolMessageType('User', (_message.Message,), {
  'DESCRIPTOR' : _USER,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.User)
  })
_sym_db.RegisterMessage(User)

InsertRequest = _reflection.GeneratedProtocolMessageType('InsertRequest', (_message.Message,), {
  'DESCRIPTOR' : _INSERTREQUEST,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.InsertRequest)
  })
_sym_db.RegisterMessage(InsertRequest)

InsertResponse = _reflection.GeneratedProtocolMessageType('InsertResponse', (_message.Message,), {
  'DESCRIPTOR' : _INSERTRESPONSE,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.InsertResponse)
  })
_sym_db.RegisterMessage(InsertResponse)

GetAllRequest = _reflection.GeneratedProtocolMessageType('GetAllRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETALLREQUEST,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetAllRequest)
  })
_sym_db.RegisterMessage(GetAllRequest)

GetAllResponse = _reflection.GeneratedProtocolMessageType('GetAllResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETALLRESPONSE,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetAllResponse)
  })
_sym_db.RegisterMessage(GetAllResponse)

GetByIDRequest = _reflection.GeneratedProtocolMessageType('GetByIDRequest', (_message.Message,), {
  'DESCRIPTOR' : _GETBYIDREQUEST,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetByIDRequest)
  })
_sym_db.RegisterMessage(GetByIDRequest)

GetByIDResponse = _reflection.GeneratedProtocolMessageType('GetByIDResponse', (_message.Message,), {
  'DESCRIPTOR' : _GETBYIDRESPONSE,
  '__module__' : 'user_service_pb2'
  # @@protoc_insertion_point(class_scope:protobuf.GetByIDResponse)
  })
_sym_db.RegisterMessage(GetByIDResponse)



_USERSERVICE = _descriptor.ServiceDescriptor(
  name='UserService',
  full_name='protobuf.UserService',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=312,
  serialized_end=517,
  methods=[
  _descriptor.MethodDescriptor(
    name='insert',
    full_name='protobuf.UserService.insert',
    index=0,
    containing_service=None,
    input_type=_INSERTREQUEST,
    output_type=_INSERTRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getAll',
    full_name='protobuf.UserService.getAll',
    index=1,
    containing_service=None,
    input_type=_GETALLREQUEST,
    output_type=_GETALLRESPONSE,
    serialized_options=None,
  ),
  _descriptor.MethodDescriptor(
    name='getByID',
    full_name='protobuf.UserService.getByID',
    index=2,
    containing_service=None,
    input_type=_GETBYIDREQUEST,
    output_type=_GETBYIDRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_USERSERVICE)

DESCRIPTOR.services_by_name['UserService'] = _USERSERVICE

# @@protoc_insertion_point(module_scope)
